name: Prune expired users

# 定时触发：UTC 16:00 （北京时间每天 00:00）
on:
  schedule:
    - cron: '0 16 * * *'

jobs:
  prune:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Prune expired user files
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const path = 'auth/users';
            const now = new Date();
            let removed = 0;
            for (const file of fs.readdirSync(path)) {
              if (!file.endsWith('.json')) continue;
              const data = JSON.parse(fs.readFileSync(`${path}/${file}`, 'utf8'));
              if (new Date(data.expired_at) <= now) {
                fs.unlinkSync(`${path}/${file}`);
                removed++;
              }
            }
            core.info(`🔍 Pruned ${removed} expired user${removed === 1 ? '' : 's'}`);

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add auth/users
          git diff --cached --quiet || git commit -m "chore: remove expired user files"
          git push
